---
pos_joint_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    shoulder_pan_joint: { p: 1000, d: 0, i: 0, i_clamp: 0 }
    shoulder_lift_joint: { p: 1000, d: 0, i: 0, i_clamp: 0 }
    elbow_joint: { p: 1000, d: 0, i: 0, i_clamp: 0 }
    wrist_1_joint: { p: 1000, d: 1, i: 0, i_clamp: 0 }
    wrist_2_joint: { p: 1000, d: 0, i: 0, i_clamp: 0 }
    wrist_7_joint: { p: 1000, d: 0, i: 0, i_clamp: 0 }
  velocity_ff:
    shoulder_pan_joint: 10.0
    shoulder_lift_joint: 10.0
    elbow_joint: 10.0
    wrist_1_joint: 10.0
    wrist_2_joint: 10.0
    wrist_3_joint: 11.0
  constraints:
    goal_time: 1
    stopped_velocity_tolerance: 1
    shoulder_pan_joint: { trajectory: 0.05, goal: 1 }
    shoulder_lift_joint: { trajectory: 0.05, goal: 1 }
    elbow_joint: { trajectory: 0.05, goal: 1 }
    wrist_1_joint: { trajectory: 0.05, goal: 1 }
    wrist_2_joint: { trajectory: 0.05, goal: 1 }
    wrist_3_joint: { trajectory: 0.05, goal: 1000 }
  stop_trajectory_duration: 0.5
  state_publish_rate: 50
  action_monitor_rate: 10
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
#gazebo_ros_control:
#  pid_gains:
#    shoulder_pan_joint: { p: 2, d: 0.05, i: 0.0001, i_clamp: 1 }
#    shoulder_lift_joint: { p: 2, d: 0.05, i: 0.0001, i_clamp: 1 }
#    elbow_joint: { p: 2, d: 0.05, i: 0.0001, i_clamp: 1 }
#    wrist_1_joint: { p: 2, d: 0.05, i: 0.0001, i_clamp: 1 }
#    wrist_2_joint: { p: 0.01, d: 0.05, i: 0.0001, i_clamp: 1 }
#    wrist_3_joint: { p: 2, d: 0.05, i: 0.0001, i_clamp: 1 }
